local.py


COUCHBASE_URL = ""


TWITTER_CONSUMER_KEY = "tlroHIz4mz32PE9YbqRx2A"
TWITTER_CONSUMER_SECERT = "eOFSXMTpJaCGkQ5tG7MwfNFxHdTLGeiYE3rfkK6Q"

TWITTER_ACCESS_TOKEN = "95257276-VuvdqXZV4WXyYMqDjkmEOuQS7zB2DavY1zu6D0V9s"
TWITTER_ACCESS_TOKEN_SECRET = "zmnKLusHGkTJzu2lkzVSJQdFBu4EBavjOfUB3x8eEA"